# Generated by Django 5.0.3 on 2026-05-13 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(verbose_name='Pregunta')),
                ('respuesta', models.TextField(verbose_name='Respuesta')),
                ('fuentes', models.TextField(blank=True, default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_rag', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta RAG',
                'verbose_name_plural': 'Consultas RAG',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('archivo', models.FileField(upload_to='documentos_rag/', verbose_name='Archivo PDF')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('indexando', 'Indexando'), ('indexado', 'Indexado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('num_chunks', models.IntegerField(default=0, verbose_name='Fragmentos indexados')),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_rag', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento RAG',
                'verbose_name_plural': 'Documentos RAG',
                'ordering': ['-created_at'],
            },
        ),
    ]
